In [1]:
import tensorflow as tf
#Tensorflow verson
print("Tensorflow Version:", tf.__version__)

Tensorflow Version: 2.21.0


In [2]:
#Define two constant tensor
tensor_a=tf.constant([[1., 2.],[3., 4.]])
tensor_b=tf.constant([[5., 6.],[7., 8.]])

#perform the matrix operation 
result=tensor_a + tensor_b
#or we can use
#result-tf.add(tensor_a, tensor_b)
print("Tensor A:\n",tensor_a)
print("Tensor B:\n",tensor_b)

Tensor A:
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Tensor B:
 tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


In [6]:
#create a tensorflow
tensor=tf.constant([[1,2,3],[4,5,6]])
#get the shape of tensor
shape=tensor.shape
print('Tensor:',tensor)
print('Tensor Shape:',shape)

Tensor: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Tensor Shape: (2, 3)


In [7]:
##tensor size
rensor=tf.constant([[1,2,3],[4,5,6]])
#get the size of tensor
size=tf.size(tensor)
print('Tensor Size:', size)

Tensor Size: tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
#Tensor Dimemnsion
tensor=tf.constant([[1,2,3],[4,5,6]])
shape=tf.shape(tensor)
#get the dimemnsion of first tensor
dim1=shape[0]
#get the dimemnsion of second tensor
dim2=shape[1]
print('Tensor Shape:', shape)
print('Dime1:', dim1)
print('Dim2:', dim2)